version: '3'
services:
  ros:
    image: robopaas/rosdocked-humble-robopaas-base-cpu:latest
    hostname: rosdocked
    environment:
      - ROS_HOSTNAME=rosdocked
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    command: rviz2
    volumes:
      - $PWD:/host
    networks:
      - x11

  novnc:  
    image: robopaas/novnc:labs
    hostname: novnc
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH= 1920
      - DISPLAY_HEIGHT= 1080
    shm_size: 2gb
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:

